[package]
name = "sbvc-gtk"
description = "A frontend for SBVC"
repository = "https://github.com/Daniikk1012/sbvc-gtk"
version = "0.2.1"
edition = "2021"
license = "GPL-3.0"

[dependencies]
sbvc_lib = "0.5"
gtk4 = "0.4"
chrono = "0.4"
